# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MyCrypto' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MyCrypto
  pod 'NVActivityIndicatorView'

  target 'MyCryptoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MyCryptoUITests' do
    # Pods for testing
  end

end
